version: 2

models:
  - name: stg_addresses
    description: >
      Table containing the addresses of the users
    columns:
      - name: address_id
        tests:
          - not_null
          - unique
      - name: address
      - name: zipcode
      - name: state
      - name: country

  - name: stg_events
    description: >
      Table containing the events of the users on the website
    columns:
      - name: event_id
        tests:
          - not_null
          - unique
      - name: session_id
        tests:
          - not_null
      - name: user_id
        tests:
          - not_null
      - name: event_type
        tests:
          - not_null
      - name: page_url
        tests:
          - not_null
      - name: created_at

  - name: stg_order_items
    description: >
      Table containing the association between an order
      and the list of products it consists of
    columns:
      - name: order_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
      - name: quantity
        tests:
          - positive_values

  - name: stg_orders
    description: >
      Table containing the orders of the users
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: promo_id
        tests:
          - dbt_utils.relationships_where:
              to: ref('stg_promo')
              field: promo_id
              from_condition: promo_id IS NOT NULL
      - name: user_id
        tests:
          - not_null
      - name: address_id
        tests:
          - not_null
      - name: created_at
      - name: order_cost
        tests:
          - not_null
          - positive_values
      - name: shipping_cost
        tests:
          - not_null
          - positive_values
      - name: order_total
        tests:
          - not_null
      - name: tracking_id
      - name: shipping_service
      - name: estimated_delivery_at
      - name: delivered_at
      - name: status

  - name: stg_products
    description: >
      Table containing the products
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
      - name: name
      - name: price
        tests:
          - not_null
          - positive_values
      - name: quantity
        tests:
          - not_null
          - positive_values

  - name: stg_promos
    description: >
      Table containing all the promos, both active and inactive ones
    columns:
      - name: promo_id
        tests:
          - not_null
          - unique
      - name: discount
        tests:
          - not_null
          - positive_values
      - name: status
        tests:
          - accepted_values:
              values: ['active', 'inactive']

  - name: stg_users
    description: >
      Table containing the users
    columns:
      - name: user_id
        tests:
          - not_null
          - unique
      - name: first_name
      - name: last_name
      - name: email
        tests:
          - not_null
      - name: phone_number
      - name: created_at
        tests:
          - not_null
      - name: updated_at
        tests:
          - not_null
      - name: address_id
        tests:
          - not_null
